tap "ddev/ddev"
tap "henkrehorst/php"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nicoverbruggen/cask"
tap "romkatv/powerlevel10k"
tap "shivammathur/php"
# Search tool like grep, but optimized for programmers
brew "ack"
# Generic-purpose lossless compression algorithm by Google
brew "brotli"
# Library and utilities for processing GIFs
brew "giflib"
# Library for manipulating PNG images
brew "libpng"
# General-purpose data compression with high compression ratio
brew "xz"
# Image format providing lossless and lossy compression for web images
brew "webp"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Macro processing language
brew "m4"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# C parser in Python
brew "pycparser"
# C Foreign Function Interface for Python
brew "cffi"
# Library for decimal floating point arithmetic
brew "mpdecimal"
# Official Amazon AWS command-line interface
brew "awscli"
# Asynchronous DNS library
brew "c-ares"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Core application library for C
brew "glib"
# Low-level library for pixel manipulation
brew "pixman"
# Vector graphics library with cross-device output support
brew "cairo"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq", restart_service: :changed
# Pack, ship and run any application as a lightweight container
brew "docker"
# Text processing system for reStructuredText
brew "docutils"
# Generic library support script
brew "libtool"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# GNU database manager
brew "gdbm"
# This library is for the GeoIP Legacy format (dat)
brew "geoip"
# Framework for layout and rendering of i18n text
brew "pango"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# GNU grep, egrep and fgrep
brew "grep"
# Text-based UI library
brew "ncurses"
# Improved top (interactive process viewer)
brew "htop"
# Apache HTTP server
brew "httpd"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Implementation of malloc emphasizing fragmentation avoidance
brew "jemalloc"
# Image manipulation library
brew "jpeg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Network authentication protocol
brew "krb5"
# DNS library written in C
brew "ldns"
# CBOR protocol implementation for C and others
brew "libcbor"
# Asynchronous event library
brew "libev"
# Provides library functionality for FIDO U2F & FIDO 2.0, including USB
brew "libfido2"
# Library to render SVG files using Cairo
brew "librsvg"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# YAML Parser
brew "libyaml"
# Get the terminal window size on macOS
brew "macos-term-size"
# Web and API based SMTP testing tool
brew "mailhog"
# UNIX manpage compiler toolset
brew "mandoc"
# Java-based project management
brew "maven"
# Open source relational database management system
brew "mysql"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx", restart_service: :changed
# Small build system for use with gyp or CMake
brew "ninja"
# Platform built on V8 to build network applications
brew "node"
# Prompt theme engine for any shell
brew "oh-my-posh"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Perl compatible regular expressions library
brew "pcre"
# General-purpose scripting language
brew "php", link: false
# General-purpose scripting language
brew "php@8.1"
# General-purpose scripting language
brew "php@8.2"
# General-purpose scripting language
brew "php@8.3"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Object-relational database system
brew "postgresql@14"
# Monitor data's progress through a pipe
brew "pv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Persistent key-value database, with built-in net interface
brew "redis"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Terminal multiplexer with VT100/ANSI terminal emulation
brew "screen"
# Tool to create intelligent and beautiful documentation
brew "sphinx-doc"
# Nodejs-based tool for optimizing SVG vector graphics files
brew "svgo"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line interface for WordPress
brew "wp-cli"
# JavaScript package manager
brew "yarn"
# General-purpose scripting language
brew "shivammathur/php/php@7.2"
# General-purpose scripting language
brew "shivammathur/php/php@7.3"
# General-purpose scripting language
brew "shivammathur/php/php@7.4", link: true
# General-purpose scripting language
brew "shivammathur/php/php@8.0"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Server and cloud storage browser
cask "cyberduck"
# Database version management tool
cask "dbngin"
# Web browser
cask "firefox"
cask "font-fira-code-nerd-font"
# Web browser
cask "google-chrome"
# Tool to optimise images to a smaller size
cask "imageoptim"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Browser for ambitious developers
cask "polypane"
# Collaboration platform for API development
cask "postman"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# MySQL/MariaDB database management
cask "sequel-ace"
# Team communication and collaboration software
cask "slack"
# Text editor for code, markup and prose
cask "sublime-text"
# Open-source code editor
cask "visual-studio-code"
# Rust-based terminal
cask "warp"
# Native desktop client for WhatsApp
cask "whatsapp"
# HTML to PDF renderer
cask "wkhtmltopdf"
# Gecko based web browser
cask "zen-browser"
vscode "aaron-bond.better-comments"
vscode "adpyke.codesnap"
vscode "ahdesign.language-antlers"
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.bookmarks"
vscode "amirmarmul.laravel-blade-vscode"
vscode "angular.ng-template"
vscode "astro-build.astro-vscode"
vscode "bierner.emojisense"
vscode "bierner.markdown-checkbox"
vscode "bierner.markdown-emoji"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "ccimage.jsonviewer"
vscode "christian-kohler.path-intellisense"
vscode "codeium.codeium"
vscode "codezombiech.gitignore"
vscode "cssho.vscode-svgviewer"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "developersoapbox.vscode-springboot-snippets"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "dotjoshjohnson.xml"
vscode "dracula-theme.theme-dracula"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "flyfly6.terminal-in-status-bar"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "formulahendry.terminal"
vscode "georgewfraser.vscode-javac"
vscode "github.github-vscode-theme"
vscode "grapecity.gc-excelviewer"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "gydunhn.vsc-essentials"
vscode "gydunhn.vsc-essentials-core"
vscode "gydunhn.vsc-essentials-material-themes"
vscode "gydunhn.vsc-essentials-themes-core"
vscode "hollowtree.vue-snippets"
vscode "ibm.output-colorizer"
vscode "jgclark.vscode-todo-highlight"
vscode "johnpapa.angular2"
vscode "jsayol.firebase-explorer"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "lauren.angular-pack"
vscode "lauren.vue-pack"
vscode "marcostazi.vs-code-drupal"
vscode "mblode.twig-language-2"
vscode "mechatroner.rainbow-csv"
vscode "mehedidracula.php-namespace-resolver"
vscode "mhutchie.git-graph"
vscode "mohsen1.prettify-json"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-de"
vscode "ms-vscode.theme-materialkit"
vscode "msjsdiag.vscode-react-native"
vscode "nadim-vscode.infinity-dark-theme"
vscode "nadim-vscode.symfony-code-snippets"
vscode "nadim-vscode.twig-code-snippets"
vscode "naumovs.color-highlight"
vscode "octref.vetur"
vscode "oderwat.indent-rainbow"
vscode "onecentlin.laravel-blade"
vscode "oracle.oracle-java"
vscode "pkief.material-icon-theme"
vscode "pkief.material-product-icons"
vscode "rangav.vscode-thunder-client"
vscode "redhat.java"
vscode "ritwickdey.liveserver"
vscode "robbowen.synthwave-vscode"
vscode "sdras.vue-vscode-snippets"
vscode "shan.code-settings-sync"
vscode "stillat-llc.vscode-antlers"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-german"
vscode "teabyii.ayu"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "tsega.drupal-8-twig-snippets"
vscode "usernamehw.errorlens"
vscode "vincaslt.highlight-matching-tag"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vitaliymaz.vscode-svg-previewer"
vscode "vivek-kasture.properties-validator"
vscode "vmware.vscode-spring-boot"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vue.volar"
vscode "wallabyjs.console-ninja"
vscode "wesbos.theme-cobalt2"
vscode "whatwedo.twig"
vscode "xdebug.php-debug"
vscode "yoyo930021.vuter"
vscode "yzhang.markdown-all-in-one"
vscode "zainchen.json"
vscode "zarifprogrammer.tailwind-snippets"
